#!/bin/sh

NAME=$(git config user.name)
EMAIL=$(git config user.email)

if [ -z "$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi

if [ -z "$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi

if cat "$1" | grep -q "Signed-off-by: $NAME <$EMAIL>"; then
    exit 0
fi

TEMP_FILE=$(mktemp)

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: $NAME <$EMAIL>" \
    --in-place "$1"

sed '/Signed-off-by:/i\
' "$1" > "$TEMP_FILE"

mv "$TEMP_FILE" "$1"
